name: Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: "diplomado-final"
          heroku_email: "luis.logs1@gmail.com"