name: Docker Build

on:
  push:
    branches: [ main, develop ]

jobs:
  test:
    name: 'Nodejs v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
          - 14
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ matrix.node }}-
      - name: Instalando Dependencias
        run: npm install
      - name: Ejecuta los test de nuestro proyecto
        run: npm run test
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "diplomado-final"
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/main:main
